# Generated by Django 2.0.5 on 2018-06-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelperQuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PersonPreferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console_api.PersonModel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console_api.HelperQuestionModel')),
            ],
        ),
        migrations.CreateModel(
            name='TouristSpotImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='data/images')),
            ],
        ),
        migrations.CreateModel(
            name='TouristSpotModel',
            fields=[
                ('key', models.CharField(default='JUh2G1Hb3PDdJw2hoiL3', max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='touristspotimagemodel',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='console_api.TouristSpotModel'),
        ),
    ]
