# Generated by Django 2.0.5 on 2018-06-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console_api', '0003_auto_20180614_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to='console_api.TouristSpotModel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='skips',
            field=models.ManyToManyField(blank=True, default=None, related_name='skips', to='console_api.TouristSpotModel'),
        ),
        migrations.AlterField(
            model_name='touristspotmodel',
            name='key',
            field=models.CharField(default='ZqtcrXGjseaoCeVgfBw9', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='console_api.TouristSpotModel'),
        ),
    ]
