# Generated by Django 2.0.5 on 2018-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console_api', '0004_auto_20180618_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspotmodel',
            name='key',
            field=models.CharField(default='d6vC8esHppDGVHAPaio4', max_length=20, primary_key=True, serialize=False),
        ),
    ]
